version: '3'
services: 
  django:
    container_name: django_app
    build:
      context: .
      dockerfile: Dockerfile.django 
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    command: celery -A videouploader worker -l info
    volumes:
      - .:/usr/src/app 
    depends_on:
      - django
      - redis
    environment:
      - AWS_ACCESS_KEY_ID=AKIAR7I3Y3YLZY42MPMZ
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_S3_REGION_NAME=ap-south-1
      - AWS_S3_BUCKET_NAME=ecowiser-videos 
      - AWS_DYNAMODB_TABLE_NAME=Subtitles

  redis:  
    image: redis:latest
